<script lang="ts">
  import HeaderShell from "$com/itemList/header/shell.svelte";
  import Loader from "$com/loader.svelte";
  import CVEList from "./cveList.svelte";

  import type { PageData } from "./$types";

  import { cveSearch } from "$state/cves";

  export let data: PageData;

  $: cves = data.cves;
</script>

<HeaderShell
  title={"CVEs in OSINTer"}
  description={"CVEs corresponding to different articles from OSINTer. Titles are generated by LLM's, so take them with a grain of salt"}
  searchSubmitable={false}
  showReadFilter={false}
  bind:searchValue={$cveSearch}
  contentType="topics"
/>

{#await $cves}
  <Loader />
{:then cves}
  <CVEList {cves} search={$cveSearch} />
{/await}
